### ISSUE TITLE
Need fix for this on README

### ISSUE THREAD

**Issue by auroraongithub** [spaceskynet/danser-gui#1]
![image](https://user-images.githubusercontent.com/86182778/156560540-ef7e419a-2358-4900-82fa-c26f53cb6671.png)

**Comment by spaceskynet** [comment]
Thanks for finding this bug! Because I changed the osr parser in the V0.2 update and forgot to change the member name from `player_name` to `username` in the Replay class. I have already fixed it, now you can redownload the v0.2 release file.
